idf_component_register(SRCS
                        "ip-speaker.c"
                        "wifi_manager.c"
                        "audio_codec_es8311.c"
                        "ring_buffer.c"
                        "i2s_player.c"
                        "udp_audio_server.c"
                        "time_sync.c"
                        "volume_storage.c"
                        "http_status_server.c"
                        "opus_decoder_wrapper.c"
                    INCLUDE_DIRS ".")
